version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - db
  web:
    build: ../d3-17anos
    ports:
      - "1337:80"
    depends_on:
      - api
  nginx:
    image: nginx:1.17-alpine
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - api
      - web
