development:
  adapter: async
  url: <%= Rails.application.credentials.fetch(:redis_url) { "redis://localhost:6379/1" } %>

test:
  adapter: test

production:
  adapter: async
  # adapter: redis
  # url: <%= Rails.application.credentials.fetch(:redis_url) { "redis://localhost:6379/1" } %>
  # channel_prefix: d317anos_production
